### ISSUE TITLE
Not published correctly?

### ISSUE THREAD

**Issue by bsnelder** [voorhoede/datocms-plugin-computed-fields#13]
This package looks very interesting, and I tried to install this plugin into DatoCMS, but ran into the follow error:
```
The plugin at https://unpkg.com/datocms-plugin-computed-fields@2.1.0/build/index.html is not responding correctly after 20 seconds.
```

Looking at the published package, it seems to be missing the build directory:
https://unpkg.com/browse/datocms-plugin-computed-fields@2.1.0/

**Comment by Marvin-Rhone** [comment]
Hello! I am running into the same issue.

**Comment by TannicArturo98** [comment]
I've installed it today and i found the same issue.

**Comment by velomovies** [comment]
Thanks for raising this issue! It seemed that publishing and building the package didn't work as expected. 
We have now updated the plugin to version `2.2.0`. If you update the plugin within Dato to the new version, it should work correctly
