### ISSUE TITLE
Missing environment ID causes issues in non-primary environments

### ISSUE THREAD

**Issue by Dandandans** [voorhoede/datocms-plugin-computed-fields#15]
I noticed that computed fields were not working in non-primary environments when using the plugin helper functions, e.g. `getModel`, because it is making the request using the primary/default environment instead of the active sandbox environment.

I created a branch that adds the current environment in addition to the `currentUserAccessToken` when initializing the `SiteClient` which seems to fix the problem. 

```
 if (ctx.currentUserAccessToken) {
    datoClient = new datocmsClient.SiteClient(ctx.currentUserAccessToken, { environment: ctx.environment },)
  }
```
I'm happy to open a PR to help resolve the issue.

**Comment by velomovies** [comment]
Thanks for raising this issue.

Great addition and simple solution to fix this problem. We have fixed this in version 2.2.2. When Dato has picked up that version you can update the plugin and get data from the correct environment
