### ISSUE TITLE
Computing a link field

### ISSUE THREAD

**Issue by guilleironhack** [voorhoede/datocms-plugin-computed-fields#17]
Thanks for this awesome plugin!

Would it be possible to compute a link field? if possible, what should be returned?

**Comment by velomovies** [comment]
Thanks for using the plugin. You certainly can use a link field. It needs a string with the ID of a linked record.
```
{
  link_field: "1234567",
}
```

Fields always need the same value as you get back from such field.

I hope this explains it enough, if so we can close this issue.
