### ISSUE TITLE
Allow getFieldValue to return object

### ISSUE THREAD

**Issue by JanStevens** [voorhoede/datocms-plugin-computed-fields#19]
Hi,

Is it possible to not cast `getFieldValue` to a string? When working with structured text you always get back an object.

https://github.com/voorhoede/datocms-plugin-computed-fields/blob/3ea2c96956f752c509a8d63a5a5898bca7593903/src/lib/getFieldValue.ts#L4

Are you open for a PR for this?

Thanks

**Comment by Siilwyn** [comment]
Hi @JanStevens what would the use-case be for this? As in why would you not cast the value it to a string?

**Comment by JanStevens** [comment]
For example generating a hidden string field from a structured text field to be used as excerpt in a modular block. If you cast a structured text field to a string it becomes unusable.

When using modular blocks and they are collapsed dato will generate the title field based on following logic

- first string field
- first structure field

This can cause issues when you have a structure text field and later in the same block a string field which less meaningful content when collapsed.

![example](https://user-images.githubusercontent.com/1540483/205580079-fd7ec09d-3592-48ec-821d-bc6df6ad0cf4.png)
![Screenshot 2022-12-05 at 08 34 19](https://user-images.githubusercontent.com/1540483/205580110-28c1fe7f-d7ca-445e-a36b-97b87361f550.png)

edit: added screenshots for clarification @Siilwyn
