### ISSUE TITLE
Where does console.log show up?

### ISSUE THREAD

**Issue by osseonews** [voorhoede/datocms-plugin-computed-fields#21]
We are trying to investigate the value of fields from the computed fields. Usually, when coding we use console.log to see the proposed output before returning it. We try to use, console.log in the code area, but the value doesn't show up anywhere. how do we access console.log value?

**Comment by Siilwyn** [comment]
The value logged in `console.log` should show up in the browser devtools.

E.g.
```
console.log({title});
return title;
```

Logs the title every time the `title` field value is changed or when I press the "Execute code" button.
