### ISSUE TITLE
Computed field is not recalculated when modifying fields of sibling (block)

### ISSUE THREAD

**Issue by hatched-grzegorz** [voorhoede/datocms-plugin-computed-fields#35]
@velomovies 
I am afraid that recent update removed triggering of the script when sibling is a block and its field is being modified.
```
{
  computed-field
  block-list {
    some-block {
      edited-text-field
    }
  }
}
```
The computed-field is not being recalculated when edited-text-field is changed.
Only saving the whole record and reopening it recalculates the field.
This worked on previous version.

**Comment by hatched-grzegorz** [comment]
Here is a video showing what I have noticed.

https://github.com/voorhoede/datocms-plugin-computed-fields/assets/60889650/b1ab63e0-9fca-4602-a79c-70b97ebdeee4

**Comment by gswierczynski** [comment]
Can be closed as resolved.
