### ISSUE TITLE
Usage on an Single Asset field causes Display Editor to become locked; unable to switch back to default

### ISSUE THREAD

**Issue by arcataroger** [voorhoede/datocms-plugin-computed-fields#42]
Hi @voorhoede, and thank you so much for this useful plug-in! I've used it many times in the past, as a former Dato customer :) I recently joined DatoCMS as a support agent, and am trying to resolve an issue another customer is now facing.

They've accidentally added this plug-in to a Single Asset field (instead of a separate text field), and are unable to switch back to the default editor without uninstalling the plugin first.

It looks like they'd previously set the computed field to return some string, and now can't figure out what to actually return it to make a valid output, so they get stuck in an error loop when trying to revert back to the default editor.

I'm looking into this issue on our end too, to see if it's something related to the plugin SDK or elsewhere in Dato. But I just wanted to mention it here too in case you have any quick ideas or workarounds :)

![image](https://github.com/voorhoede/datocms-plugin-computed-fields/assets/11964962/a409817e-e0ce-491a-ba0c-23cb067e48c3)

### Steps to reproduce

- Have a single asset field
- Add the Computed Fields plugin
- Set the single asset field display type to the Computed Field
- In the Computed Field code, have it return some simple string like `return 'test'` and click Save.
- Edit the schema again and try to change the field type back to Default editor. It errors out.

**Comment by arcataroger** [comment]
I've also reported this issue internally, and will report back here if we find any additional information.

**Comment by arcataroger** [comment]
@voorhoede We shipped a fix for this internally, so users can revert fields back to the default editor if need be.

But do you think there is a legitimate use case for single-asset fields being able to be displayed as a Computed Field? I'm asking just because I wonder if it would be safer to exclude that field type from this plugin altogether. What do you think?

Thanks again for your work on this!

**Comment by velomovies** [comment]
Hi @arcataroger thanks for the heads up and nice to see that's fixed!

One of the main things we consider with this plugin is that there should be no limitations regarding the possibilities. I think there are ways to implement this in a single-asset field, but that's for the users to figure out themselves. It should open endless ways to implement it and have the freedom to use it if you need it. So thats why I don't want to exclude this field type.

**Comment by arcataroger** [comment]
Gotcha. Thanks for the explanation!
