### ISSUE TITLE
Not returning anything

### ISSUE THREAD

**Issue by CraigChamberlain** [voorhoede/datocms-plugin-computed-fields#5]
I tried a few slightly more complicated ideas, to access an objects sub-components.  Then I tried just returning a string:
`return 'SomeText'`

I tried giving the plugin readonly and then full rights with different API keys.  I've tried in chrome and firefox always the same an empty box.

This should be a really amazing adition.  Was hoping to use to make a api query on a datetime object and put write back a string of particular format.  If I can't even write back a string literal it's not looking so hopeful.

**Comment by velomovies** [comment]
Hi @CraigChamberlain, Sorry to hear that it doesn't work for you. We have fixed a small bug regarding not updating data with a newly installed plugin. As soon as you can update or download version 1.2.2 that should be fixed.

I hope that will solve your problem.

**Comment by CraigChamberlain** [comment]
Great, thanks velomovies.  It looks like the version available is still 1.2.1 not sure how/when the version number is bumped on dato?

**Comment by velomovies** [comment]
Dato should pick up the new version automatically. That can take some time. I hope it will be updated in the next few days.

**Comment by velomovies** [comment]
Hi @CraigChamberlain, you can now update the plugin to 1.2.2. Let us know if your issue is solved

**Comment by CraigChamberlain** [comment]
This is all fine now.  However, it only works at all with development mode enabled.
