### ISSUE TITLE
How to access Local based content?

### ISSUE THREAD

**Issue by nilesh2293** [voorhoede/datocms-plugin-computed-fields#6]
Hello Folks,
Hope you are doing great. I am using the Datocms computed fields plugin for my project. It's really awesome.
Just one doubt. how can I access current locale fields when localization is enabled.
I tried following way but what I am looking for is a more dynamic way to handle this thing:
return `${title['en-IN']}`

**Comment by velomovies** [comment]
Hi @nilesh2293, 
Happy to hear you like the plugin!
We didn't test anything with locales in previous versions, but this should be a great addition. In version 1.3.0 we have added an extra variable `locale` which dynamically returns the current locale. In that version you can do `title[locale]`.

You should be able to update the plugin via Dato and use it in you projects. 

I hope this is what you are looking for.

**Comment by nilesh2293** [comment]
Thanks for enabling locale.
